### ISSUE TITLE
further documentation of assumePureVars

### ISSUE THREAD

**Issue by matthewleon** [Pauan/rollup-plugin-purs#12] opened 2017-04-08 09:32 UTC
Could you give an example/counterexample in the documentation for what you mean by variable assignment being "pure"?

Also, I quickly browsed through the code and was unable to find any uses of it, just mentions in the TODOs. Perhaps you could give an example of the kind of optimization setting `assumePureVars` to `true` permits?

**Comment by Pauan** [comment] 2017-04-08 10:48
@matthewleon PureScript uses curried functions, and often times a function is created by calling an existing function:

```js
function add(x) {
  return function (y) {
    return x + y;
  };
}

// add5 is a function that adds 5 to its argument
var add5 = add(5);
```

In the above example, even if `add5` is not used, it will be included in the bundle, because `rollup-plugin-purs` does not know whether the `add(5)` call has side effects or not, so it errs on the side of caution and leaves it in.

If you use `assumePureVars`, then `rollup-plugin-purs` can assume that `add5` is pure, and therefore it will be removed.

For a concrete example of this problem, see https://github.com/Pauan/rollup-plugin-purs/issues/8. The `unsafeCompare`, `EQ`, `GT`, `LT`, `unsafeCompareImpl__private_do_not_use_export__0`, and `unsafeCompareImpl__private_do_not_use_export__0$0__private_do_not_use_uncurried__5__1$0` variables are included, even though none of them are used.

And this was just from a tiny program: the problem is even worse in a big program.

The `psc-bundle` program already makes similar assumptions, so if your code works with `psc-bundle` then it should also work with `assumePureVars`

----

The `assumePureVars` setting is used [here](https://github.com/Pauan/rollup-plugin-purs/blob/22e5acef283ad7e71820a71bb6fe2266ec406d88/src/dead-code.js#L54).

**Comment by matthewleon** [comment] 2017-04-08 11:45
Thank you very much for a fantastic, and thorough, explanation. Is it worth paraphrasing this and including it in the docs somewhere?

**Comment by matthewleon** [comment] 2017-04-08 11:47
Would also be nice to document any potential gotchas with this. I naively assume that practices that would break this would be either a) abusing the FFI or b) abusing any functions in the standard library marked as "unsafe". Is there anything else one should avoid?

**Comment by Pauan** [comment] 2017-04-09 22:28
@matthewleon I think there's only three situations where this could be a problem:

1. Doing weird stuff with the FFI (e.g. calling an impure function, assigning the result to a variable, never using that variable, and expecting the impure function to still be called)

2. The same as 1, but using an unsafe function in PureScript (which are rarely used)

3. The same as 1, except you are importing a JavaScript library (e.g. using npm / bower)

In general it shouldn't cause any problems, especially for PureScript code, but it might be a problem when using a JavaScript library.

I updated the README to give an explanation for `assumePureVars`

----

Also, if you are using the uncurrying optimization, then [dead code elimination works fine with currying](https://github.com/Pauan/rollup-plugin-purs/issues/8#issuecomment-292816485), even when not using `assumePureVars`.

But it still includes `_LT2`, `_GT2`, and `_EQ2`, because of the `.value` assignment (which is impure). So `assumePureVars` is currently needed to solve cases like that.

If the PureScript compiler changed its code output, then maybe `assumePureVars` wouldn't be needed anymore.

Alternatively, I can try to make the pure detection smarter in `rollup-plugin-purs`, which is also doable.

**Closed by Pauan** 2017-04-09 22:28 UTC
